version: '3'
services:
  edx:
    image: python:2.7
    working_dir: /edx-platform
    volumes:
      - .:/edx-platform
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=lms.envs.devstack
    command: >
      bash -c "
        echo 'This legacy edX platform requires complex setup including:' &&
        echo '- Python 2.7 (EOL since 2020)' &&
        echo '- MySQL 5.6' &&
        echo '- MongoDB 2.6' &&
        echo '- Memcached' &&
        echo '- RabbitMQ' &&
        echo '- Elasticsearch' &&
        echo '' &&
        echo 'Due to its age and complexity, running this locally is not straightforward.' &&
        echo 'This codebase is best used for:' &&
        echo '1. Code analysis and studying legacy patterns' &&
        echo '2. Understanding technical debt in large Django applications' &&
        echo '3. Planning modernization strategies' &&
        echo '' &&
        echo 'For a working Django app, consider using a modern Django starter instead.' &&
        tail -f /dev/null
      " 