# Generated by Django 4.2.7 on 2025-07-25 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninganalytics',
            name='average_session_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='learninganalytics',
            name='reading_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='learninganalytics',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='learninganalytics',
            name='video_watch_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
